spring.application.name=ScheduLink-Backend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/schedulink_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:schedulink}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
